### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alexstaeding** [CharlieTap/synk#9]
I looked but was unable to find any kind of license for this project.

A project (even a public one) is considered all rights reserved without a license which prevents any legal usage. (See [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository))

The idea behind this project seems interesting to me and I would like to try it out, but I cannot consider it until there is a license.

**Comment by CharlieTap** [comment]
Hey @alexstaeding 

The licensing is now updated so feel free to play around with the library!
